version: "3.6"

services:
  postgres:
    image: "custom-postgres"
    ports:
      - "5432:5432"      
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - persistence
